# 使用OpenJDK 21作为基础镜像
FROM openjdk:21-jdk-slim

# 设置工作目录
WORKDIR /app

# 复制jar包（从jar目录复制）
COPY jar/*.jar /app/app.jar

# 创建配置目录
RUN mkdir -p /app/config /app/logs

# 设置JVM参数
#ENV JAVA_OPTS="-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -Dfile.encoding=UTF-8 -Duser.timezone=GMT+08"

# 暴露端口
EXPOSE 8085


# 启动应用
ENTRYPOINT ["sh", "-c", "java -jar /app/app.jar --spring.config.additional-location=/app/config/"]
